export const OBEvent = {
  AUTO_PLAY_NUM_SCORE: 'AUTO_PLAY_NUM_SCORE',
  PAUSE_AUTO_PLAY: 'PAUSE_AUTO_PLAY',

  AUTO_PLAY_XML_SCORE: 'AUTO_PLAY_XML_SCORE',
  PAUSE_XML_AUTO_PLAY: 'PAUSE_XML_AUTO_PLAY',

  CHANGE_WALLPAPER: 'CHANGE_WALLPAPER'
}